### PR TITLE
Multiprotocol functions refactor

### PR DESCRIPTION
**Pull request by maht**
I think these changes would result in a less complex implementation and usage. If approved, then `multiprotocol_functions` branch could be squashed and tried to be contributed upstream instead of current one.

### CODE REVIEW

**Comment by yamt** [comment]
* i'm not sure how MQTT_USE_CUSTOM_SOCKET_HANDLE is supposed to be used.
* for the upsteam i guess an example would be nice.

**Comment by maht** [comment]
>     * i'm not sure how MQTT_USE_CUSTOM_SOCKET_HANDLE is supposed to be used.
> 
>     * for the upsteam i guess an example would be nice.

Yes, I agree. Sorry for the lack of documentation, as I was working on it. Definitively some example has to be included if we expect it to be accepted upstream.

The idea is the one expressed in https://github.com/midokura/nuttx-external/blob/fbc854843910246917745441f12dff431063967d/evp_agent/linux/Makefile#L11:
 * You can put the forward declaration statement of your customized type (if needed, like in a struct object) inside `MQTT_USE_CUSTOM_SOCKET_HANDLE` instead of just declaring it empty. This could be skipped if a more opaque `void *` is used instead, but keeping actual types makes usage more type robust I guess.
 * At the same time the value of `mqtt_pal_socket_handle` can be defined by compiler arguments too, like in that case being a pointer to the struct.
 * And finally, as before, the functions for the desired implementations can be included by defining the corresponding preprocesor macros.

```
-DMQTT_USE_CUSTOM_SOCKET_HANDLE='struct pal_socket;'
-Dmqtt_pal_socket_handle='struct pal_socket *'
-DMQTT_USE_MBEDTLS
-DMQTT_USE_TCP
```

If you don't like abusing `MQTT_USE_CUSTOM_SOCKET_HANDLE` for this, maybe a new preprocesor definition can be added, but in this case I think it could be acceptable, as it is needed implicitly anyway.

**Comment by yamt** [comment]
> > ```
> > * i'm not sure how MQTT_USE_CUSTOM_SOCKET_HANDLE is supposed to be used.
> > 
> > * for the upsteam i guess an example would be nice.
> > ```
> 
> Yes, I agree. Sorry for the lack of documentation, as I was working on it. Definitively some example has to be included if we expect it to be accepted upstream.
> 
> The idea is the one expressed in https://github.com/midokura/nuttx-external/blob/fbc854843910246917745441f12dff431063967d/evp_agent/linux/Makefile#L11:
> 
>     * You can put the forward declaration statement of your customized type (if needed, like in a struct object) inside `MQTT_USE_CUSTOM_SOCKET_HANDLE` instead of just declaring it empty. This could be skipped if a more opaque `void *` is used instead, but keeping actual types makes usage more type robust I guess.
> 
>     * At the same time the value of `mqtt_pal_socket_handle` can be defined by compiler arguments too, like in that case being a pointer to the struct.
> 
>     * And finally, as before, the functions for the desired implementations can be included by defining the corresponding preprocesor macros.
> 
> 
> ```
> -DMQTT_USE_CUSTOM_SOCKET_HANDLE='struct pal_socket;'
> -Dmqtt_pal_socket_handle='struct pal_socket *'
> -DMQTT_USE_MBEDTLS
> -DMQTT_USE_TCP
> ```
> 
> If you don't like abusing `MQTT_USE_CUSTOM_SOCKET_HANDLE` for this, maybe a new preprocesor definition can be added, but in this case I think it could be acceptable, as it is needed implicitly anyway.

thank you for the explanation.

right now, it seems that MQTT_USE_CUSTOM_SOCKET_HANDLE is expected to be used as
https://github.com/LiamBindle/MQTT-C/issues/22#issuecomment-429503664

that is,
```
struct pal_socket;
typedef struct pal_socket *mqtt_pal_socket_handle;
#include <mqtt.h>
```

do you have a problem with this?
(just asking. i have no idea as i have not used it.)

**Comment by lulingar** [comment]
This is more of a style issue, but we don't want to delay this any further. If we end up being required to comply with such usage way, then we can change, but there are features and work being blocked by not having this feature merged. What do you think @yamt, can you accept the current status?

**Comment by yamt** [comment]
@lulingar are you asking me not to ask questions?

**Comment by lulingar** [comment]
@yamt this is old water, we've been through this already, so you should know better, that I'm simply asking you to accept the current implementation in the interest of not blocking the rest of remaining work.
@maht can give the details as to why your proposal doesn't quite provide value against the extra effort and time it requires.

**Comment by yamt** [comment]
@lulingar what does "old water" mean? i tried google but found nothing obvious.

i thought @maht is doing this way (having a PR here) because he wanted feedback.
and i provided feedback.
and now you are asking me to "accept" it, suggesting i'm blocking his work?
i'm a bit puzzled.

when i needed some MQTT-C changes in the past,
i just pushed it to my private fork and made nuttx-external use it until the changes are accepted in the upstream.
i have no problem if @maht wants to do that way.

**Comment by lulingar** [comment]
"old water" is just an expression I saw a few times, to mean something already seen.

I'll express it perhaps more clearly. The question is ok and @maht should reply of course. But in the meantime, can you approve the PR?

**Comment by maht** [comment]
> right now, it seems that MQTT_USE_CUSTOM_SOCKET_HANDLE is expected to be used as
> [LiamBindle#22 (comment)](https://github.com/LiamBindle/MQTT-C/issues/22#issuecomment-429503664)
> 
> that is,
> 
> ```
> struct pal_socket;
> typedef struct pal_socket *mqtt_pal_socket_handle;
> #include <mqtt.h>
> ```
> 
> do you have a problem with this?
> (just asking. i have no idea as i have not used it.)

Sorry, it seems my answer to your question was lost for some reason or I did not hit the send button :(

I think it can be done but it requires to add these two lines as an additional source file during the build of MQTT-C (if done as a library at least) which requires more "effort" than simply adding the preprocessor definitions. I could try it, but it would have take some time so that is the reason I proposed to leave for later (and the reason @Luis put that comment). Since in my view, if we want to integrate these changes in the other private repositories, it is better the changes are in the Midokura public fork, not in my personal public fork. But your feedback is very welcome as always, nobody is questioning that :)

Btw, using the typedef would imply that all the `#define mqtt_pak_socket_handle ...` should be changed to typedefs too, it isn't?

**Comment by yamt** [comment]
> > right now, it seems that MQTT_USE_CUSTOM_SOCKET_HANDLE is expected to be used as
> > [LiamBindle#22 (comment)](https://github.com/LiamBindle/MQTT-C/issues/22#issuecomment-429503664)
> > that is,
> > ```
> > struct pal_socket;
> > typedef struct pal_socket *mqtt_pal_socket_handle;
> > #include <mqtt.h>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > do you have a problem with this?
> > (just asking. i have no idea as i have not used it.)
> 
> Sorry, it seems my answer to your question was lost for some reason or I did not hit the send button :(
> 
> I think it can be done but it requires to add these two lines as an additional source file during the build of MQTT-C (if done as a library at least) which requires more "effort" than simply adding the preprocessor definitions. I could try it, but it would have take some time so that is the reason I proposed to leave for later (and the reason @luis put that comment). Since in my view, if we want to integrate these changes in the other private repositories, it is better the changes are in the Midokura public fork, not in my personal public fork. But your feedback is very welcome as always, nobody is questioning that :)

ok.

> 
> Btw, using the typedef would imply that all the `#define mqtt_pak_socket_handle ...` should be changed to typedefs too, it isn't?

i agree that it's cleaner to use either of typedef or #define consistently.
but i guess it works as far as one of them are chosen by #ifdef.

**Review by yamt — APPROVED** [review]

**Pull request merged**
